# Generated by Django 5.0.4 on 2024-04-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название привычки')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место')),
                ('time', models.TimeField(blank=True, default='12:00:00', null=True, verbose_name='время')),
                ('action', models.CharField(blank=True, max_length=100, null=True, verbose_name='действие')),
                ('date', models.DateField(blank=True, null=True, verbose_name='дата')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('reward', models.CharField(blank=True, max_length=250, null=True, verbose_name='вознаграждение')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='длительность выполнения')),
                ('periodicity', models.IntegerField(blank=True, default=1, null=True, verbose_name='периодичность')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit.habittracker', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
